#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information() {
    local line=$(dig "$2"."$1" | awk '/ANSWER SECTION/ {getline; print}')
    if [ -z "$line" ]; then
        echo "No destination found for subdomain $2"
    else
        local record_type=$(echo "$line" | awk '{print $1}')
        local destination=$(echo "$line" | awk '{print $NF}')
        echo "The subdomain $2 is a $record_type record and points to $destination"
    fi
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi