#!/bin/bash

function audit_subdomain() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=(www lb-01 web-01 web-02)
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short $sub.$domain | awk 'NR==1{print $1}')
        destination=$(dig +short $sub.$domain | awk 'NR==1{print $2}')

        if [ -z "$destination" ]; then
            echo "No destination found for subdomain $sub"
        else
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

audit_subdomain "$1" "$2"